name: "Hello World"
description: "Greet someone and record the time"
inputs:
  repo-token:
    description: "Should be set to the GITHUB_TOKEN environment variable"
    required: true
runs:
  using: "node12"
  main: "index.js"
